{{ if .Values.essentials.inspike.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy" }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
    app: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
  template:
    metadata:
      labels:
        app: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
    spec:
      imagePullSecrets:
      {{- range .Values.essentials.inspike.PullSecrets }}
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
          image: {{ .Values.essentials.inspike.image | default "registry.gitlab.com/yesodot/rnd/terminal-rabaz/shared/spike-proxy-service:latest"}}
          ports:
            - containerPort: {{ .Values.essentials.inspike.port | default "3000"}}
              name: http
          env:
          - name: MODE
            value: "incoming"
          - name: PORT
            value: {{ .Values.essentials.inspike.port | quote }}
          - name: INCOMING_SERVICES
            value: {{ .Values.essentials.inspike.incoming_services | quote }}
          - name: SPIKE_PUBLIC_KEY_FULL_PATH
            value: {{ .Values.essentials.inspike.public_key_full_path }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
spec:
  selector:
    app: {{ .Values.essentials.inspike.name | default "incoming-spike-proxy"}}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.essentials.inspike.port | default "3000"}}
      targetPort: {{ .Values.essentials.inspike.port | default "3000"}}
{{ end }}