{{- if .Values.essentials.minio.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.essentials.minio.name | default "minio" }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
    app: {{ .Values.essentials.minio.name | default "minio" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.essentials.minio.name | default "minio" }}
  template:
    metadata:
      labels:
        app: {{ .Values.essentials.minio.name | default "minio" }}
    spec:
      containers:
        - name: {{ .Values.essentials.minio.name | default "minio" }}
          image: "quay.io/minio/minio:latest"
          command:
            - "/bin/sh"
            - "-ce"
            - "/usr/bin/docker-entrypoint.sh minio server /data --address :{{ .Values.essentials.minio.port }} --console-address :{{ .Values.essentials.minio.UIPort }} "
          ports:
            - name: minio
              containerPort: {{ .Values.essentials.minio.port | default "9000"}}
            - name: minio-console
              containerPort: {{ .Values.essentials.minio.UIPort | default "9001"}}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.essentials.minio.rootUser}}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.essentials.minio.rootPassword}}
          
      
        
---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.essentials.minio.name | default "minio" }}
spec:
  selector:
    app: {{ .Values.essentials.minio.name | default "minio" }}
  ports:
    - name: http
      port: {{ .Values.essentials.minio.port  | default "9000"}}
      protocol: TCP
      targetPort: {{ .Values.essentials.minio.port | default "9000"}}
    - name: api
      port: {{ .Values.essentials.minio.UIPort | default "9001"}}
      protocol: TCP
      targetPort: {{ .Values.essentials.minio.UIPort | default "9001"}}

  


---

{{- if .Values.essentials.minio.ingress.enabled -}}

{{- $fullName := .Values.essentials.minio.name | default "minio"  -}}
{{- $servicePort := .Values.essentials.minio.UIPort  -}}
{{- $ingressPath := .Values.essentials.minio.ingress.path -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.essentials.minio.name | default "minio" }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
    app: {{ .Values.essentials.minio.name | default "minio" }}
spec:
{{- if .Values.essentials.minio.ingress.tls }}
  tls:
  {{- range .Values.essentials.minio.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.essentials.minio.ingress.hosts }}
    - http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
      {{- if . }}
      host: {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}

{{- end }}
