{{- $replicaset := default false .Values.essentials.mongo.replicaset -}}
{{- if .Values.essentials.mongo.enabled -}}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.essentials.mongo.name | default "mongo" }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
spec:
      imagePullSecrets:
      {{- range .Values.essentials.mongo.PullSecrets }}
        - name: {{ . }}
      {{- end }}
      containers:
      {{- if $replicaset }}
      - name: {{ .Values.essentials.mongo.name | default "mongo"}}
        image: {{ .Values.essentials.mongo.image | default "mongo:4" }}
        command: [ "/usr/bin/mongod", "--replSet", "{{ .Values.essentials.mongo.replica_name | default "rs2"}}" , "--bind_ip_all", "--wiredTigerCacheSizeGB", "1" ]
        ports:
          - containerPort: {{ .Values.essentials.mongo.port | default "27017"}}
            name: {{ .Values.essentials.mongo.name | default "mongo"}}
          
      - name: "mongo-setup"
        image: {{ .Values.essentials.mongo.image | default "harborreg-2.northeurope.cloudapp.azure.com/library/mongo-setup:0.0.3" }}
        command: ["bash", "-c", "/config/wait-for-it.sh {{ .Values.essentials.mongo.name | default "mongo"}}:27017 -- /config/mongo-setup.sh"]
        env:
        - name: HOST_NAME
          value: {{ .Values.essentials.mongo.name | default "mongo"}}
        - name: RPL_NAME
          value: {{ .Values.essentials.mongo.replica_name | default "rs2"}}
        {{- else }}
        - name: {{ .Values.essentials.mongo.name | default "mongo"}}
          image: {{ .Values.essentials.mongo.image | default "mongo"}}
        {{- end }}
      restartPolicy: OnFailure      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.essentials.mongo.name | default "mongo"}}
spec:
  selector:
    app: {{ .Values.essentials.mongo.name | default "mongo"}}
  ports:
    - protocol: TCP
      name: mongo
      port: {{ .Values.essentials.mongo.port | default 27017 }}
      targetPort: {{ .Values.essentials.mongo.port | default 27017}}
---
{{- end -}}
