{{ if .Values.essentials.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
  labels:
    {{- include "master-chart.labels" . | nindent 4 }}
    app: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
  template:
    metadata:
      labels:
        app: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
    spec:
      containers:
        - name: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
          image: {{ .Values.essentials.rabbitmq.name | default "rabbitmq:3-management" }}
          ports:
            - containerPort: {{ .Values.essentials.rabbitmq.amqpport | default "5672"}}
              name: api
            - containerPort: {{ .Values.essentials.rabbitmq.httpport | default "15672"}}
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
spec:
  selector:
    app: {{ .Values.essentials.rabbitmq.name | default "rabbit" }}
  ports:
    - protocol: TCP
      name: api
      port: {{ .Values.essentials.rabbitmq.amqpport | default "5672"}}
      targetPort: {{ .Values.essentials.rabbitmq.amqpport | default "5672"}}

    - protocol: TCP
      name: http
      port: {{ .Values.essentials.rabbitmq.httpport | default "15672"}}
      targetPort: {{ .Values.essentials.rabbitmq.httpport | default "15672"}}
{{ end }}